### ISSUE TITLE
Create a Slack command integration

### ISSUE THREAD

**Issue by shaharsol** [tikalk/ttt-slack#3]
The objective is to enable our company's employees to report their working hours via simple Slack command.

The backend for reporting working hours is an [Anuko Time Tracker](https://timetracker.anuko.com) that is installed on our premises. For the development process I have created a test account in the hosted version of Anuko.
url: https://timetracker.anuko.com/login.php
username: ttt-slack-staging
password: 12345678
You'll find a single project, and two tasks that you can use to report time with.

The Anuko system is a rather old, API-less system, so we have built a proxy server that enables sending time tracking commands to it. For the development process I have deployed such a proxy server that runs against the Anuko hosted version.
url: https://ttt-proxy-staging.herokuapp.com/

the proxy server has a single command -- `/track-time` -- and here's how to use it:

```
curl -X POST -d "login=ttt-slack-staging" -d "password=12345678" -d "project=ttt-slack" -d "task=consulting" -d "start=09:00" -d "finish=10:00" -d "date=2016-03-12" -d "note=hello" https://ttt-proxy-staging.herokuapp.com/track-time
```

On success, the proxy will return http 200, otherwise it returns 500 with an error message.

Your task is to implement these features:

`/ttt username {username}` to save the users' Anuko username in the database
`/ttt password {username}` to save the users' Anuko password in the database
`/ttt project {project-name}` to save the users' default project in the database
`/ttt task {task-name}` to save the users' default task in the database
`/ttt in` to be used by the user to mark a beginning of a day. Save the current time in the database
`/ttt out` to post a time tracking to Anuko, based on all the information that is already saved in the database, and the current date.
`/ttt track {project-name} {task-name} {in-time} {out-time}` for cases where the default project and task are not to be used, or for any other reason, for example the user forgot to `/ttt in` when they entered their office in the morning :)

Of course the unique username you should use for identifying users will be the one provided by Slack. Please always respond an ephemeral human readable response. For example, After a successful saving of a default project, let the user know it was successful. If there was a problem with tracking the working hours, the employee should be alerted about it. 

Please make the proxy server endpoint configurable via ENV vars, i.e. `process.env.TTT_PROXY_URI`

codemill$60

**Comment by khuongduybui** [comment]
Do you have a testing Slack team / account I can use? If so, I'll take this.

**Comment by biks152207** [comment]
i would have taken this task but unfortunately i dont have paypal account.

**Comment by shaharsol** [comment]
@khuongduybui I don't have one, but isn't it free to create? anyway, I see that @LindepNet grabbed the task. @LindepNet pls let me know if you have any questions.

**Comment by ghost** [comment]
Hi @shaharsol no questions for the moment, i looked code the code yesterday and try to understand the problematic. I will work on it today.
Have you a dead line ?

**Comment by shaharsol** [comment]
No deadline.

**Comment by ghost** [comment]
I'm no longer on the task in codemill, is it normal ?

**Comment by shaharsol** [comment]
You sure? I see you as the developer of the task. Maybe you're looking at
the "clients" dashboard and not the "developers" dashboard?
Anyway, I know I said no deadline, but please don't let it linger.

**Comment by ghost** [comment]
Yes i'm sure, in my account there is no task in developpement.
Sure, i keep you update tomorrow of my progress.

**Comment by ghost** [comment]
Ok task come back, think the probleme was the production update

**Comment by shaharsol** [comment]
@LindepNet any progress?

**Comment by ghost** [comment]
Not really for the moment ..

**Comment by shaharsol** [comment]
@LindepNet OK, it can wait another day, but please, if you think you can't get to it let me know and I'll pass it to someone more available right now.

**Comment by ghost** [comment]
After some hours to fail start application on my computer (windows) i have donwload application on my own server but always same message : 

`{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version`

**Comment by shaharsol** [comment]
@KyleCartmell @khuongduybui @Gagege

Care to work on this? http://codemill.io/task/56efa809eb8038030069d169

**Comment by blitmap** [comment]
These Slack commands would save the supplied information in Mongo to then be combined together for a POST to the real Anuko server behind the proxy, correct?

A POST to "the real Anuko" only happens with a `/ttt out` or with `/ttt track {project-name} {task-name} {in-time} {out-time}`, yes?

**Comment by shaharsol** [comment]
Correct

**Comment by blitmap** [comment]
I think I can manage this, but my Mongo experience is pretty basic.  May I have a few hours of good faith and if I can't come up with anything I'll ungrab it?

I am assuming a user can only be working on 1 task at a time and not several.

I have setting data from Slack working correctly, I'm working on POST'ing to Anuko now.

**Comment by blitmap** [comment]
Okay, I have it correctly posting to Anuko through the reverse proxy.  The code I've written is incredibly messy, though.  I think I need some guidance on how to properly organize this.  I'm sure I should be using promises instead of callbacks so it's cleaner.

I'm going to fix a small problem I'm having with the `note` field and then I'll push it as-is before trying to clean it up.  I'm just not very familiar with webapp structure or if I should be creating other routes so I could use some feedback.

**Comment by khuongduybui** [comment]
Create the pull request, I can give a quick CR :)

**Comment by blitmap** [comment]
I found a bug in Anuko I think - when you POST a task that has a time which overlaps an already recorded time, it silently ignores it.  This has nothing to do with what I've written - Anuko itself just sends 200 and "time tracked" like it was successful.

**Comment by blitmap** [comment]
How do I associate the pull request I created with this issue?  I forgot how Codemill does this... :eyes:
